const audioLinks = {
  "Adele - Easy On Me": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Adele%20-%20Easy%20On%20Me",
  "Adele - Rolling in the Deep": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Adele%20-%20Rolling%20in%20the%20Deep",
  "Adele - Skyfall": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Adele%20-%20Skyfall",
  "Adele - Someone Like You": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Adele%20-%20Someone%20Like%20You",
  "Anne-Marie - 2002": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Anne-Marie%20-%202002",
  "Ariana Grande - 7 rings": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Ariana%20Grande%20-%207%20rings",
  "Ariana Grande - we can't be friends (wait for your love)": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Ariana%20Grande%20-%20we%20can%27t%20be%20friends%20%28wait%20for%20your%20love%29",
  "Ariana Grande, Nicki Minaj - Side To Side": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Ariana%20Grande%2C%20Nicki%20Minaj%20-%20Side%20To%20Side",
  "Artemas - i like the way you kiss me": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Artemas%20-%20i%20like%20the%20way%20you%20kiss%20me",
  "Benson Boone - Beautiful Things": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Benson%20Boone%20-%20Beautiful%20Things",
  "Beyonce - Halo": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Beyonc%C3%A9%20-%20Halo",
  "Billie Eilish - BIRDS OF A FEATHER": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Billie%20Eilish%20-%20BIRDS%20OF%20A%20FEATHER",
  "Billie Eilish - CHIHIRO": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Billie%20Eilish%20-%20CHIHIRO",
  "Billie Eilish - i love you": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Billie%20Eilish%20-%20i%20love%20you",
  "Billie Eilish - WILDFLOWER": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Billie%20Eilish%20-%20WILDFLOWER",
  "Black Eyed Peas - I Gotta Feeling": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Black%20Eyed%20Peas%20-%20I%20Gotta%20Feeling",
  "Bruno Mars - Just the Way You Are": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Bruno%20Mars%20-%20Just%20the%20Way%20You%20Are",
  "Bruno Mars - The Lazy Song": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Bruno%20Mars%20-%20The%20Lazy%20Song",
  "Calum Scott, Leona Lewis - You Are The Reason - Duet Version": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Calum%20Scott%2C%20Leona%20Lewis%20-%20You%20Are%20The%20Reason%20-%20Duet%20Version",
  "Carly Rae Jepsen - Call Me Maybe": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Carly%20Rae%20Jepsen%20-%20Call%20Me%20Maybe",
  "Chappell Roan - Good Luck, Babe!": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Chappell%20Roan%20-%20Good%20Luck%2C%20Babe%21",
  "Chappell Roan - Pink Pony Club": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Chappell%20Roan%20-%20Pink%20Pony%20Club",
  "Charlie Puth, Selena Gomez - We Don't Talk Anymore (feat. Selena Gomez)": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Charlie%20Puth%2C%20Selena%20Gomez%20-%20We%20Don%27t%20Talk%20Anymore%20%28feat.%20Selena%20Gomez%29",
  "Christina Perri - a thousand years": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Christina%20Perri%20-%20a%20thousand%20years",
  "Clean Bandit, Sean Paul, Anne-Marie - Rockabye": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Clean%20Bandit%2C%20Sean%20Paul%2C%20Anne-Marie%20-%20Rockabye",
  "Celine Dion - I'm Alive": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/C%C3%A9line%20Dion%20-%20I%27m%20Alive",
  "David Kushner - Daylight": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/David%20Kushner%20-%20Daylight",
  "DAWN, ALMA - Angels": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/DAWN%2C%20ALMA%20-%20Angels",
  "DJ Snake, Justin Bieber - Let Me Love You": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/DJ%20Snake%2C%20Justin%20Bieber%20-%20Let%20Me%20Love%20You",
  "Ed Sheeran - Perfect": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Ed%20Sheeran%20-%20Perfect",
  "Ed Sheeran - Shape of You": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Ed%20Sheeran%20-%20Shape%20of%20You",
  "Ed Sheeran - Thinking out Loud": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Ed%20Sheeran%20-%20Thinking%20out%20Loud",
  "Fifth Harmony, Kid Ink - Worth It (feat. Kid Ink)": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Fifth%20Harmony%2C%20Kid%20Ink%20-%20Worth%20It%20%28feat.%20Kid%20Ink%29",
  "Fifth Harmony, Ty Dolla $ign - Work from Home (feat. Ty Dolla $ign)": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Fifth%20Harmony%2C%20Ty%20Dolla%20%24ign%20-%20Work%20from%20Home%20%28feat.%20Ty%20Dolla%20%24ign%29",
  "Gracie Abrams - That's So True": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Gracie%20Abrams%20-%20That%E2%80%99s%20So%20True",
  "Halsey - Without Me": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Halsey%20-%20Without%20Me",
  "Harry Styles - As It Was": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Harry%20Styles%20-%20As%20It%20Was",
  "Harry Styles - Sign of the Times": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Harry%20Styles%20-%20Sign%20of%20the%20Times",
  "Henry Moodie - drunk text": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Henry%20Moodie%20-%20drunk%20text",
  "Jennifer Lopez, Pitbull - On The Floor": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Jennifer%20Lopez%2C%20Pitbull%20-%20On%20The%20Floor",
  "John Legend - All of Me": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/John%20Legend%20-%20All%20of%20Me",
  "Justin Bieber, Chance the Rapper - Confident - Single Version": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Justin%20Bieber%2C%20Chance%20the%20Rapper%20-%20Confident%20-%20Single%20Version",
  "Justin Bieber, Ludacris - Baby": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Justin%20Bieber%2C%20Ludacris%20-%20Baby",
  "Justin Bieber, Quavo - Intentions": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Justin%20Bieber%2C%20Quavo%20-%20Intentions",
  "Justin Timberlake - CAN'T STOP THE FEELING! (from DreamWorks Animation's 'TROLLS')": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Justin%20Timberlake%20-%20CAN%27T%20STOP%20THE%20FEELING%21%20%28from%20DreamWorks%20Animation%27s%20%27TROLLS%27%29",
  "Justin Timberlake - Mirrors": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Justin%20Timberlake%20-%20Mirrors",
  "Katy Perry - Roar": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Katy%20Perry%20-%20Roar",
  "Katy Perry, Juicy J - Dark Horse": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Katy%20Perry%2C%20Juicy%20J%20-%20Dark%20Horse",
  "Lady Gaga - Always Remember Us This Way": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Lady%20Gaga%20-%20Always%20Remember%20Us%20This%20Way",
  "Lady Gaga - Bad Romance": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Lady%20Gaga%20-%20Bad%20Romance",
  "Lady Gaga - Poker Face": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Lady%20Gaga%20-%20Poker%20Face",
  "Lady Gaga, Bradley Cooper - Shallow": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Lady%20Gaga%2C%20Bradley%20Cooper%20-%20Shallow",
  "Lady Gaga, Bruno Mars - Die With A Smile": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Lady%20Gaga%2C%20Bruno%20Mars%20-%20Die%20With%20A%20Smile",
  "Lana Del Rey - Summertime Sadness": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Lana%20Del%20Rey%20-%20Summertime%20Sadness",
  "Lauv - I Like Me Better": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Lauv%20-%20I%20Like%20Me%20Better",
  "Lewis Capaldi - Someone You Loved": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Lewis%20Capaldi%20-%20Someone%20You%20Loved",
  "Lola Young - Messy": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Lola%20Young%20-%20Messy",
  "Mark Ronson, Bruno Mars - Uptown Funk (feat. Bruno Mars)": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Mark%20Ronson%2C%20Bruno%20Mars%20-%20Uptown%20Funk%20%28feat.%20Bruno%20Mars%29",
  "Maroon 5 - Girls Like You": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Maroon%205%20-%20Girls%20Like%20You",
  "Maroon 5 - Memories": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Maroon%205%20-%20Memories",
  "Maroon 5 - Sugar": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Maroon%205%20-%20Sugar",
  "Miley Cyrus - Flowers": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Miley%20Cyrus%20-%20Flowers",
  "MIRA - Duro": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/MIRA%20-%20Duro",
  "MIRA - Love Again": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/MIRA%20-%20Love%20Again",
  "MIRA - Ring Ring": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/MIRA%20-%20Ring%20Ring",
  "Naughty Boy, Sam Smith - La La La": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Naughty%20Boy%2C%20Sam%20Smith%20-%20La%20La%20La",
  "NSYNC - Bye Bye Bye": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/NSYNC%20-%20Bye%20Bye%20Bye",
  "One Direction - Night Changes": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/One%20Direction%20-%20Night%20Changes",
  "OneRepublic - Counting Stars": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/OneRepublic%20-%20Counting%20Stars",
  "OneRepublic - I Ain't Worried": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/OneRepublic%20-%20I%20Ain%27t%20Worried",
  "P!nk, Nate Ruess - Just Give Me a Reason (feat. Nate Ruess)": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/P%21nk%2C%20Nate%20Ruess%20-%20Just%20Give%20Me%20a%20Reason%20%28feat.%20Nate%20Ruess%29",
  "Passenger - Let Her Go": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Passenger%20-%20Let%20Her%20Go",
  "Pitbull, AFROJACK, Ne-Yo, Nayer - Give Me Everything (feat. Nayer)": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Pitbull%2C%20AFROJACK%2C%20Ne-Yo%2C%20Nayer%20-%20Give%20Me%20Everything%20%28feat.%20Nayer%29",
  "Rihanna - Diamonds": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Rihanna%20-%20Diamonds",
  "ROSE, Bruno Mars - APT": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/ROS%C3%89%2C%20Bruno%20Mars%20-%20APT",
  "Sabrina Carpenter - Espresso": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Sabrina%20Carpenter%20-%20Espresso",
  "Sabrina Carpenter - Please Please Please": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Sabrina%20Carpenter%20-%20Please%20Please%20Please",
  "Sabrina Carpenter - Taste": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Sabrina%20Carpenter%20-%20Taste",
  "Sam Smith, Normani - Dancing With A Stranger (with Normani)": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Sam%20Smith%2C%20Normani%20-%20Dancing%20With%20A%20Stranger%20%28with%20Normani%29",
  "Sean Kingston, Justin Bieber - Eenie Meenie": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Sean%20Kingston%2C%20Justin%20Bieber%20-%20Eenie%20Meenie",
  "Sean Paul, Dua Lipa - No Lie": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Sean%20Paul%2C%20Dua%20Lipa%20-%20No%20Lie",
  "Shakira, Wyclef Jean - Hips Don't Lie (feat. Wyclef Jean)": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Shakira%2C%20Wyclef%20Jean%20-%20Hips%20Don%27t%20Lie%20%28feat.%20Wyclef%20Jean%29",
  "Shawn Mendes, Camila Cabello - Senorita": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Shawn%20Mendes%2C%20Camila%20Cabello%20-%20Se%C3%B1orita",
  "Sia - Chandelier": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Sia%20-%20Chandelier",
  "Sia - Cheap Thrills": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Sia%20-%20Cheap%20Thrills",
  "Stephen Sanchez - Until I Found You": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Stephen%20Sanchez%20-%20Until%20I%20Found%20You",
  "Taylor Swift - Blank Space": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Taylor%20Swift%20-%20Blank%20Space",
  "Taylor Swift - Shake It Off": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Taylor%20Swift%20-%20Shake%20It%20Off",
  "Teddy Swims - Bad Dreams": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Teddy%20Swims%20-%20Bad%20Dreams",
  "The Goo Goo Dolls - Iris": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/The%20Goo%20Goo%20Dolls%20-%20Iris",
  "The Pussycat Dolls, Snoop Dogg - Buttons - Final Edit Version": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/The%20Pussycat%20Dolls%2C%20Snoop%20Dogg%20-%20Buttons%20-%20Final%20Edit%20Version",
  "The Weeknd - Blinding Lights": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/The%20Weeknd%20-%20Blinding%20Lights",
  "The Weeknd - Save Your Tears": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/The%20Weeknd%20-%20Save%20Your%20Tears",
  "Timbaland, OneRepublic - Apologize": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Timbaland%2C%20OneRepublic%20-%20Apologize",
  "TOESUP, Smiley - Two Feet": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/TOESUP%2C%20Smiley%20-%20Two%20Feet",
  "TOESUP, Smiley, DJ Dark - Two Feet (DJ Dark Remix)": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/TOESUP%2C%20Smiley%2C%20DJ%20Dark%20-%20Two%20Feet%20%28DJ%20Dark%20Remix%29",
  "Tom Odell - Another Love": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Tom%20Odell%20-%20Another%20Love",
  "Tones And I - Dance Monkey": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/Tones%20And%20I%20-%20Dance%20Monkey",
  "ZAYN, Sia - Dusk Till Dawn (feat. Sia)": "https://res.cloudinary.com/dy0urslke/video/upload/v1/audio_uploads/ZAYN%2C%20Sia%20-%20Dusk%20Till%20Dawn%20%28feat.%20Sia%29",
};


export {audioLinks};